// =====================================================================
// siteContentSchema.js
//
// Schema + defaults for the store's editable site content.
// Mirrors tapas-store/src/utils/defaultContent.js — keep the two in sync.
// =====================================================================

export const DEFAULT_CONTENT = {
  brand: {
    name: 'Your brand',
    tagline: '',
    primary_color: '#037171',
    primary_color_dark: '#025555',
    primary_color_light: '#0a8a8a',
    accent_color: '#00B9AE',
    accent_color_dark: '#00A09A',
    cream_color: '#E6CCBE',
    sand_color: '#F5E9DD',
    heading_font: 'Space Grotesk',
    body_font: 'Inter',
  },
  contact: {
    phone: '', email: '', address: '',
    hours_weekdays: '', hours_saturday: '', hours_sunday: '',
  },
  home: {
    hero_eyebrow: '',
    hero_headline_line1: 'Your headline here',
    hero_headline_line2: '',
    hero_description: 'A short paragraph that sets the tone for your homepage.',
    search_placeholder: 'Search…',
    staff_picks_eyebrow: '', staff_picks_title: '', staff_picks_subtitle: '',
    cafe_story_headline_line1: '', cafe_story_headline_line2: '', cafe_story_body: '',
  },
  about: {
    hero_eyebrow: '',
    hero_headline_line1: 'About us',
    hero_headline_line2: '',
    hero_subtitle: '',
    hero_bg_image_url: '',
    story_pull_quote: '',
    story_body_1: '', story_body_2: '', story_body_3: '',
    values_heading: '', values_eyebrow: '',
    values_1_title: '', values_1_body: '',
    values_2_title: '', values_2_body: '',
    values_3_title: '', values_3_body: '',
    values_4_title: '', values_4_body: '',
  },
  offers: {
    hero_eyebrow: '',
    hero_headline_line1: 'Offers',
    hero_headline_line2: '',
    hero_description: '',
    plans_footer: '',
    why_join_eyebrow: '', why_join_heading: '',
    why_join_1_title: '', why_join_1_body: '',
    why_join_2_title: '', why_join_2_body: '',
    why_join_3_title: '', why_join_3_body: '',
    why_join_4_title: '', why_join_4_body: '',
    cta_headline: '', cta_body: '',
  },
  newsletter: {
    eyebrow: '',
    headline: 'Subscribe for updates',
    description: 'Join our newsletter to get updates in your inbox.',
  },
  images: {
    home_hero_bg_url: '',
    cafe_story_bg_url: '',
  },
  plans: {
    basic_tier: 'Basic', basic_price: '', basic_period: '/month', basic_tagline: '', basic_features: '',
    silver_tier: 'Silver', silver_price: '', silver_period: '/month', silver_tagline: '', silver_features: '',
    gold_tier: 'Gold', gold_price: '', gold_period: '/month', gold_tagline: '', gold_features: '',
  },
  catalog: {
    header_eyebrow: '',
    header_title: 'Catalog',
    header_subtitle_prefix: '',
    header_subtitle_suffix: '',
  },
  footer: {
    template: 'classic',
    tagline: '',
    copyright_text: 'All rights reserved.',
    quick_links_heading: 'Quick Links',
    hours_heading: 'Opening Hours',
    contact_heading: 'Contact',
    // Optional custom quick-links. If non-empty, replaces the default
    // Home/Books/Offers/About column on the storefront.
    custom_links: [],
  },
  header: {
    template: 'classic',
    logo_emoji: '📚',
    nav_home: 'Home',
    nav_books: 'Books',
    nav_offers: 'Offers',
    nav_about: 'About',
    login_label: 'Login',
    signup_label: 'Sign Up',
    search_placeholder: 'Search books...',
    // Optional custom nav. If non-empty, replaces the 4 default links
    // (Home/Books/Offers/About) in every header template.
    custom_nav_links: [],
  },
  visibility: {
    home_hero: true,
    home_genres: true,
    home_staff_picks: true,
    home_new_arrivals: true,
    home_cafe_story: true,
    home_newsletter: true,
    about_values: true,
    about_visit: true,
    about_contact_form: true,
    offers_plans: true,
    offers_why_join: true,
    offers_cta: true,
  },
  styles: {
    home_hero_headline_size: 72,
    home_hero_headline_align: 'left',
    about_hero_headline_size: 64,
    about_hero_headline_align: 'center',
    offers_hero_headline_size: 64,
    offers_hero_headline_align: 'center',
  },
  layout: {
    home_section_order: 'hero,genres,staff_picks,new_arrivals,cafe_story,newsletter',
  },
  typography: {
    heading_xxl_size:   72,
    heading_xl_size:    42,
    heading_l_size:     32,
    heading_color:      '',
    heading_weight:     '800',
    body_size:          16,
    body_color:         '',
    eyebrow_size:       11,
    eyebrow_tracking:   '2.5px',
  },
  buttons: {
    radius:         50,
    padding_x:      32,
    padding_y:      14,
    font_size:      15,
    font_weight:    '700',
    text_transform: 'none',
    letter_spacing: '0.5px',
  },
  element_styles: {},
  section_styles: {
    home_hero_padding_top:      80,
    home_hero_padding_bottom:   100,
    home_hero_bg_color:         '',
    home_hero_bg_image:         '',
    home_staff_picks_padding_top:    80,
    home_staff_picks_padding_bottom: 80,
    home_staff_picks_bg_color:       '',
    home_staff_picks_bg_image:       '',
    home_cafe_story_padding_top:    100,
    home_cafe_story_padding_bottom: 100,
    home_cafe_story_bg_color:       '',
    home_cafe_story_bg_image:       '',
    about_hero_padding_top:    100,
    about_hero_padding_bottom: 120,
    about_hero_bg_color:       '',
    about_hero_bg_image:       '',
    offers_hero_padding_top:    80,
    offers_hero_padding_bottom: 40,
    offers_hero_bg_color:       '',
    offers_hero_bg_image:       '',
    // Per-section color / alignment overrides for header + footer + main
    // content sections. Empty string means "use brand defaults".
    header_bg_color:            '',
    header_text_color:          '',
    header_link_color:          '',
    header_link_active_color:   '',
    footer_bg_color:            '',
    footer_text_color:          '',
    footer_heading_color:       '',
    footer_link_color:          '',
    footer_text_align:          'left',
    home_genres_bg_color:       '',
    home_genres_text_align:     'left',
    home_new_arrivals_bg_color: '',
    home_new_arrivals_text_align: 'left',
    home_newsletter_bg_color:   '',
    home_newsletter_text_align: 'center',
  },

  // Webflow-style page builder (Phase 1). Mirrors the shape in
  // tapas-store/src/utils/defaultContent.js. The editor will surface
  // this in Phase 2; for now it just needs to round-trip through the
  // schema's deep-merge unchanged.
  pages: {
    home:    { meta: { title: 'Home',    description: '' }, blocks: [] },
    about:   { meta: { title: 'About',   description: '' }, blocks: [] },
    catalog: { meta: { title: 'Shop',    description: '' }, blocks: [] },
    offers:  { meta: { title: 'Offers',  description: '' }, blocks: [] },
    blog:    { meta: { title: 'Journal', description: '' }, blocks: [] },
    events:  { meta: { title: 'Events',  description: '' }, blocks: [] },
  },
  block_templates: [],
};

export const CONTENT_SCHEMA = [
  {
    key: 'brand',
    title: 'Brand',
    subtitle: 'Name, tagline, colors, and fonts shared across every page.',
    icon: '🎨',
    fields: [
      { key: 'name',                label: 'Brand name',        type: 'text',  hint: 'Shown in the navbar and footer.' },
      { key: 'tagline',             label: 'Brand tagline',     type: 'text',  hint: 'Small line under the name.' },
      { key: 'primary_color',       label: 'Primary color',     type: 'color', hint: 'Dark brown. Navbar, hero, headlines.' },
      { key: 'primary_color_dark',  label: 'Primary — darker shade',  type: 'color' },
      { key: 'primary_color_light', label: 'Primary — lighter shade', type: 'color' },
      { key: 'accent_color',        label: 'Accent color',      type: 'color', hint: 'Warm gold. Prices, CTAs, highlights.' },
      { key: 'accent_color_dark',   label: 'Accent — darker shade',   type: 'color' },
      { key: 'cream_color',         label: 'Background cream',  type: 'color', hint: 'Page background.' },
      { key: 'sand_color',          label: 'Sand accent',       type: 'color', hint: 'Book cover placeholder.' },
      { key: 'heading_font',        label: 'Heading font',      type: 'font',  hint: 'Any Google Font.' },
      { key: 'body_font',           label: 'Body font',         type: 'font',  hint: 'Any Google Font.' },
    ],
  },
  {
    key: 'contact',
    title: 'Contact',
    subtitle: 'Phone, email, address, hours shown in About and the footer.',
    icon: '📍',
    fields: [
      { key: 'phone',          label: 'Phone',          type: 'text' },
      { key: 'email',          label: 'Email',          type: 'text' },
      { key: 'address',        label: 'Address',        type: 'textarea' },
      { key: 'hours_weekdays', label: 'Mon–Fri hours',  type: 'text' },
      { key: 'hours_saturday', label: 'Saturday hours', type: 'text' },
      { key: 'hours_sunday',   label: 'Sunday hours',   type: 'text' },
    ],
  },
  {
    key: 'home',
    title: 'Home page',
    subtitle: 'Headlines and copy for the home page.',
    icon: '🏠',
    fields: [
      { key: 'hero_eyebrow',              label: 'Hero eyebrow',                    type: 'text' },
      { key: 'hero_headline_line1',       label: 'Hero headline — line 1',          type: 'text' },
      { key: 'hero_headline_line2',       label: 'Hero headline — line 2 (italic)', type: 'text' },
      { key: 'hero_description',          label: 'Hero description',                type: 'textarea' },
      { key: 'search_placeholder',        label: 'Search placeholder',              type: 'text' },
      { key: 'staff_picks_eyebrow',       label: 'Staff picks eyebrow',             type: 'text' },
      { key: 'staff_picks_title',         label: 'Staff picks title',               type: 'text' },
      { key: 'staff_picks_subtitle',      label: 'Staff picks subtitle',            type: 'textarea' },
      { key: 'cafe_story_headline_line1', label: 'Cafe headline — line 1',          type: 'text' },
      { key: 'cafe_story_headline_line2', label: 'Cafe headline — line 2 (italic)', type: 'text' },
      { key: 'cafe_story_body',           label: 'Cafe story body',                 type: 'textarea' },
    ],
  },
  {
    key: 'home',
    parent: 'home',
    title: 'Home — Hero carousel',
    subtitle: 'Rotating slides under the hero headline. Use for events, new arrivals, announcements. Leave slide titles empty to hide.',
    icon: '🎠',
    fields: [
      { key: 'hero_carousel_enabled',          label: 'Show hero carousel',                  type: 'select', options: [
        { value: true,  label: 'Yes — show slides' },
        { value: false, label: 'No — hide carousel' },
      ] },
      { key: 'hero_carousel_autoplay_seconds', label: 'Autoplay interval (seconds)',         type: 'number', hint: 'How often slides rotate. Set to 0 to disable autoplay.' },

      { key: 'hero_slide_1_eyebrow',           label: 'Slide 1 — eyebrow',                   type: 'text' },
      { key: 'hero_slide_1_title',             label: 'Slide 1 — title',                     type: 'text' },
      { key: 'hero_slide_1_body',              label: 'Slide 1 — body',                      type: 'textarea' },
      { key: 'hero_slide_1_cta_label',         label: 'Slide 1 — button label',              type: 'text' },
      { key: 'hero_slide_1_cta_link',          label: 'Slide 1 — button link',               type: 'text', hint: 'Internal path like /offers or full URL.' },
      { key: 'hero_slide_1_image',             label: 'Slide 1 — background image',          type: 'image' },

      { key: 'hero_slide_2_eyebrow',           label: 'Slide 2 — eyebrow',                   type: 'text' },
      { key: 'hero_slide_2_title',             label: 'Slide 2 — title',                     type: 'text' },
      { key: 'hero_slide_2_body',              label: 'Slide 2 — body',                      type: 'textarea' },
      { key: 'hero_slide_2_cta_label',         label: 'Slide 2 — button label',              type: 'text' },
      { key: 'hero_slide_2_cta_link',          label: 'Slide 2 — button link',               type: 'text' },
      { key: 'hero_slide_2_image',             label: 'Slide 2 — background image',          type: 'image' },

      { key: 'hero_slide_3_eyebrow',           label: 'Slide 3 — eyebrow',                   type: 'text' },
      { key: 'hero_slide_3_title',             label: 'Slide 3 — title',                     type: 'text' },
      { key: 'hero_slide_3_body',              label: 'Slide 3 — body',                      type: 'textarea' },
      { key: 'hero_slide_3_cta_label',         label: 'Slide 3 — button label',              type: 'text' },
      { key: 'hero_slide_3_cta_link',          label: 'Slide 3 — button link',               type: 'text' },
      { key: 'hero_slide_3_image',             label: 'Slide 3 — background image',          type: 'image' },
    ],
  },
  {
    key: 'images',
    title: 'Images',
    subtitle: 'Background photos used on hero sections. Leave blank for the default gradient.',
    icon: '🖼️',
    fields: [
      { key: 'home_hero_bg_url',  label: 'Home hero background',  type: 'image', hint: 'Large photo behind the home page headline.' },
      { key: 'cafe_story_bg_url', label: 'Cafe story background', type: 'image', hint: 'Photo behind the "More than a bookstore" section.' },
    ],
  },
  {
    key: 'about',
    title: 'About — Hero & story',
    subtitle: 'The About page hero and the three-paragraph story block.',
    icon: '📖',
    fields: [
      { key: 'hero_eyebrow',        label: 'Hero eyebrow',                    type: 'text' },
      { key: 'hero_headline_line1', label: 'Hero headline — line 1',          type: 'text' },
      { key: 'hero_headline_line2', label: 'Hero headline — line 2 (italic)', type: 'text' },
      { key: 'hero_subtitle',       label: 'Hero subtitle',                   type: 'textarea' },
      { key: 'hero_bg_image_url',   label: 'Hero background image',           type: 'image' },
      { key: 'story_pull_quote',    label: 'Story pull quote',                type: 'text' },
      { key: 'story_body_1',        label: 'Story paragraph 1',               type: 'textarea' },
      { key: 'story_body_2',        label: 'Story paragraph 2',               type: 'textarea' },
      { key: 'story_body_3',        label: 'Story paragraph 3',               type: 'textarea' },
    ],
  },
  {
    key: 'about_values',
    parent: 'about',
    title: 'About — Values block',
    subtitle: 'The "Four things we care about" section with 01/02/03/04 cards.',
    icon: '💎',
    fields: [
      { key: 'values_eyebrow',      label: 'Eyebrow',                 type: 'text' },
      { key: 'values_heading',      label: 'Section heading',         type: 'text' },
      { key: 'values_1_title',      label: 'Value 1 — title',         type: 'text' },
      { key: 'values_1_body',       label: 'Value 1 — body',          type: 'textarea' },
      { key: 'values_2_title',      label: 'Value 2 — title',         type: 'text' },
      { key: 'values_2_body',       label: 'Value 2 — body',          type: 'textarea' },
      { key: 'values_3_title',      label: 'Value 3 — title',         type: 'text' },
      { key: 'values_3_body',       label: 'Value 3 — body',          type: 'textarea' },
      { key: 'values_4_title',      label: 'Value 4 — title',         type: 'text' },
      { key: 'values_4_body',       label: 'Value 4 — body',          type: 'textarea' },
    ],
  },
  {
    key: 'offers',
    title: 'Offers — Hero',
    subtitle: 'The top of the Offers page.',
    icon: '💳',
    fields: [
      { key: 'hero_eyebrow',        label: 'Hero eyebrow',                    type: 'text' },
      { key: 'hero_headline_line1', label: 'Hero headline — line 1',          type: 'text' },
      { key: 'hero_headline_line2', label: 'Hero headline — line 2 (italic)', type: 'text' },
      { key: 'hero_description',    label: 'Hero description',                type: 'textarea' },
      { key: 'plans_footer',        label: 'Fine print below plans',          type: 'text' },
    ],
  },
  {
    key: 'offers_why_join',
    parent: 'offers',
    title: 'Offers — Why join',
    subtitle: 'The "What a membership actually buys you" block.',
    icon: '⭐',
    fields: [
      { key: 'why_join_eyebrow',    label: 'Eyebrow',                  type: 'text' },
      { key: 'why_join_heading',    label: 'Section heading',          type: 'text' },
      { key: 'why_join_1_title',    label: 'Item 1 — title',           type: 'text' },
      { key: 'why_join_1_body',     label: 'Item 1 — body',            type: 'textarea' },
      { key: 'why_join_2_title',    label: 'Item 2 — title',           type: 'text' },
      { key: 'why_join_2_body',     label: 'Item 2 — body',            type: 'textarea' },
      { key: 'why_join_3_title',    label: 'Item 3 — title',           type: 'text' },
      { key: 'why_join_3_body',     label: 'Item 3 — body',            type: 'textarea' },
      { key: 'why_join_4_title',    label: 'Item 4 — title',           type: 'text' },
      { key: 'why_join_4_body',     label: 'Item 4 — body',            type: 'textarea' },
    ],
  },
  {
    key: 'offers_cta',
    parent: 'offers',
    title: 'Offers — Final CTA',
    subtitle: 'The "Ready to join?" block at the bottom of the page.',
    icon: '🎯',
    fields: [
      { key: 'cta_headline', label: 'CTA headline', type: 'text' },
      { key: 'cta_body',     label: 'CTA body',     type: 'textarea' },
    ],
  },
  {
    key: 'newsletter',
    title: 'Newsletter',
    subtitle: 'The subscribe strip at the bottom of the home page.',
    icon: '📬',
    fields: [
      { key: 'eyebrow',     label: 'Eyebrow (emoji ok)', type: 'text' },
      { key: 'headline',    label: 'Headline',           type: 'text' },
      { key: 'description', label: 'Description',        type: 'textarea' },
    ],
  },
  {
    key: 'plans_basic',
    parent: 'plans',
    title: 'Membership — Basic',
    subtitle: 'Entry-level plan card on the Offers page.',
    icon: '🥉',
    fields: [
      { key: 'basic_tier',     label: 'Tier name',  type: 'text' },
      { key: 'basic_price',    label: 'Price',      type: 'text', hint: 'Include the currency symbol, e.g. "₹300".' },
      { key: 'basic_period',   label: 'Period',     type: 'text', hint: '"/month", "/year", etc.' },
      { key: 'basic_tagline',  label: 'Tagline',    type: 'text', hint: 'Short italic phrase under the tier name.' },
      { key: 'basic_features', label: 'Features',   type: 'textarea', hint: 'One feature per line. Each line becomes a ✓ bullet.' },
    ],
  },
  {
    key: 'plans_silver',
    parent: 'plans',
    title: 'Membership — Silver',
    subtitle: 'The "Most Popular" mid-tier plan.',
    icon: '🥈',
    fields: [
      { key: 'silver_tier',     label: 'Tier name',  type: 'text' },
      { key: 'silver_price',    label: 'Price',      type: 'text' },
      { key: 'silver_period',   label: 'Period',     type: 'text' },
      { key: 'silver_tagline',  label: 'Tagline',    type: 'text' },
      { key: 'silver_features', label: 'Features',   type: 'textarea', hint: 'One per line.' },
    ],
  },
  {
    key: 'plans_gold',
    parent: 'plans',
    title: 'Membership — Gold',
    subtitle: 'Top tier plan.',
    icon: '🥇',
    fields: [
      { key: 'gold_tier',     label: 'Tier name',  type: 'text' },
      { key: 'gold_price',    label: 'Price',      type: 'text' },
      { key: 'gold_period',   label: 'Period',     type: 'text' },
      { key: 'gold_tagline',  label: 'Tagline',    type: 'text' },
      { key: 'gold_features', label: 'Features',   type: 'textarea', hint: 'One per line.' },
    ],
  },
  {
    key: 'catalog',
    title: 'Catalog page',
    subtitle: 'The /books page header.',
    icon: '📚',
    fields: [
      { key: 'header_eyebrow',          label: 'Eyebrow',          type: 'text' },
      { key: 'header_title',            label: 'Title',            type: 'text' },
      { key: 'header_subtitle_suffix',  label: 'Subtitle (after book count)', type: 'textarea', hint: 'Book count is prepended automatically.' },
    ],
  },
  {
    key: 'header',
    title: 'Header / Navbar',
    subtitle: 'Template, logo emoji, nav link labels, and CTA buttons in the top bar.',
    icon: '🧭',
    fields: [
      { key: 'template', label: 'Layout template', type: 'select', hint: 'Pick one of 10 navbar layouts.', options: [
        { value:'classic',        label: '1. Classic (logo · nav · CTAs)' },
        { value:'centered',       label: '2. Centered (2 rows, logo center)' },
        { value:'split',          label: '3. Split (nav left · logo center)' },
        { value:'minimal',        label: '4. Minimal (logo + single CTA)' },
        { value:'search_forward', label: '5. Search-forward (big search bar)' },
        { value:'double_decker',  label: '6. Double-decker (info strip + nav)' },
        { value:'transparent',    label: '7. Transparent (overlays hero)' },
        { value:'pill_nav',       label: '8. Pill nav (rounded container)' },
        { value:'accent_bar',     label: '9. Accent bar (thick top border)' },
        { value:'announcement',   label: '10. Announcement (marquee + nav)' },
      ] },
      { key: 'logo_emoji',     label: 'Logo emoji',   type: 'text', hint: 'Shown next to the brand name in the navbar.' },
      { key: 'nav_home',       label: 'Home link',    type: 'text', hint: 'Default label. Ignored if Custom nav links is non-empty.' },
      { key: 'nav_books',      label: 'Books link',   type: 'text' },
      { key: 'nav_offers',     label: 'Offers link',  type: 'text' },
      { key: 'nav_about',      label: 'About link',   type: 'text' },
      {
        key: 'custom_nav_links', label: 'Custom nav links', type: 'array',
        hint: 'If any rows are added, these replace the four default Home/Books/Offers/About links on every header template. Great for adding a "Press" or "Team" page.',
        itemDefaults: { label: 'New link', href: '/' },
        itemFields: [
          { key: 'label', label: 'Label', type: 'text' },
          { key: 'href',  label: 'Link',  type: 'text', hint: 'Use a relative path like /about, or a full URL like https://…' },
        ],
      },
      { key: 'login_label',    label: 'Login button', type: 'text' },
      { key: 'signup_label',   label: 'Sign Up button', type: 'text' },
      { key: 'search_placeholder', label: 'Search placeholder', type: 'text' },
    ],
  },
  {
    key: 'footer',
    title: 'Footer',
    subtitle: 'Template, tagline, copyright, and section headings at the bottom of every page.',
    icon: '🦶',
    fields: [
      { key: 'template', label: 'Layout template', type: 'select', hint: 'Pick one of 10 footer layouts.', options: [
        { value:'classic',          label: '1. Classic (4 columns)' },
        { value:'minimal',          label: '2. Minimal (single row)' },
        { value:'big_visit',        label: '3. Big visit (address focus)' },
        { value:'newsletter_first', label: '4. Newsletter first (subscribe strip)' },
        { value:'centered',         label: '5. Centered column' },
        { value:'two_column',       label: '6. Two-column (brand + links)' },
        { value:'dark_gold',        label: '7. Dark + gold accents' },
        { value:'three_column',     label: '8. Three-column compact' },
        { value:'social_first',     label: '9. Social / contact pills top' },
        { value:'map_embed',        label: '10. Map embed (Google Maps)' },
      ] },
      { key: 'tagline',             label: 'Tagline',              type: 'textarea', hint: 'Short description next to the logo.' },
      { key: 'quick_links_heading', label: 'Quick Links heading',  type: 'text' },
      {
        key: 'custom_links', label: 'Custom Quick Links', type: 'array',
        hint: 'If any rows are added, these replace the default Home/Books/Offers/About column in the footer.',
        itemDefaults: { label: 'New link', href: '/' },
        itemFields: [
          { key: 'label', label: 'Label', type: 'text' },
          { key: 'href',  label: 'Link',  type: 'text' },
        ],
      },
      { key: 'hours_heading',       label: 'Opening Hours heading', type: 'text' },
      { key: 'contact_heading',     label: 'Contact heading',      type: 'text' },
      { key: 'copyright_text',      label: 'Copyright text',       type: 'text', hint: 'Appears after "© {year} {brand name}".' },
    ],
  },
  {
    key: 'visibility',
    title: 'Show / hide sections',
    subtitle: 'Turn entire sections on or off without touching code.',
    icon: '👁',
    fields: [
      { key: 'home_hero',          label: 'Home — Hero',                      type: 'toggle' },
      { key: 'home_genres',        label: 'Home — Browse by genre',           type: 'toggle' },
      { key: 'home_staff_picks',   label: 'Home — Staff picks',               type: 'toggle' },
      { key: 'home_new_arrivals',  label: 'Home — New & noteworthy',          type: 'toggle' },
      { key: 'home_cafe_story',    label: 'Home — Cafe story',                type: 'toggle' },
      { key: 'home_newsletter',    label: 'Home — Newsletter',                type: 'toggle' },
      { key: 'about_values',       label: 'About — Values (01/02/03/04)',     type: 'toggle' },
      { key: 'about_visit',        label: 'About — Visit us (hours)',         type: 'toggle' },
      { key: 'about_contact_form', label: 'About — Contact form',             type: 'toggle' },
      { key: 'offers_plans',       label: 'Offers — Membership tiers',        type: 'toggle' },
      { key: 'offers_why_join',    label: 'Offers — Why join',                type: 'toggle' },
      { key: 'offers_cta',         label: 'Offers — Final CTA',               type: 'toggle' },
    ],
  },
  {
    key: 'styles',
    title: 'Text styles',
    subtitle: 'Font size and alignment for the main headlines.',
    icon: '🔠',
    fields: [
      { key: 'home_hero_headline_size',   label: 'Home hero — size (px)',    type: 'number', hint: 'Clamped 32–96.' },
      { key: 'home_hero_headline_align',  label: 'Home hero — alignment',    type: 'select', options: [{ value:'left', label:'Left' }, { value:'center', label:'Center' }, { value:'right', label:'Right' }] },
      { key: 'about_hero_headline_size',  label: 'About hero — size (px)',   type: 'number' },
      { key: 'about_hero_headline_align', label: 'About hero — alignment',   type: 'select', options: [{ value:'left', label:'Left' }, { value:'center', label:'Center' }, { value:'right', label:'Right' }] },
      { key: 'offers_hero_headline_size', label: 'Offers hero — size (px)',  type: 'number' },
      { key: 'offers_hero_headline_align',label: 'Offers hero — alignment',  type: 'select', options: [{ value:'left', label:'Left' }, { value:'center', label:'Center' }, { value:'right', label:'Right' }] },
    ],
  },
  {
    key: 'layout',
    title: 'Home section order',
    subtitle: 'Reorder sections on the home page.',
    icon: '🔀',
    fields: [
      { key: 'home_section_order', label: 'Home page sections', type: 'sectionOrder',
        options: [
          { value: 'hero',         label: 'Hero (headline + search)' },
          { value: 'genres',       label: 'Browse by genre' },
          { value: 'staff_picks',  label: 'Handpicked by our librarians' },
          { value: 'new_arrivals', label: 'New & noteworthy' },
          { value: 'cafe_story',   label: 'Cafe story block' },
          { value: 'newsletter',   label: 'Newsletter signup' },
        ]
      },
    ],
  },
  {
    key: 'typography',
    title: 'Typography',
    subtitle: 'Size, color, and weight for headings and body text site-wide.',
    icon: '🔤',
    fields: [
      { key: 'heading_xxl_size', label: 'Biggest headings — size (px)', type: 'number', min: 24, max: 120, hint: 'Hero h1 on Home, About, Offers.' },
      { key: 'heading_xl_size',  label: 'Section titles — size (px)',   type: 'number', min: 18, max: 72,  hint: 'e.g. "Handpicked by our librarians".' },
      { key: 'heading_l_size',   label: 'Sub-section titles — size (px)', type: 'number', min: 14, max: 48 },
      { key: 'heading_color',    label: 'Heading color override',       type: 'color',  hint: 'Leave blank to use brand primary color.' },
      { key: 'heading_weight',   label: 'Heading weight',               type: 'select', options: [
        { value:'500', label:'Medium' }, { value:'600', label:'Semibold' }, { value:'700', label:'Bold' }, { value:'800', label:'Extra bold' }, { value:'900', label:'Black' },
      ]},
      { key: 'body_size',        label: 'Body text — size (px)',        type: 'number', min: 12, max: 24 },
      { key: 'body_color',       label: 'Body text color override',     type: 'color' },
      { key: 'eyebrow_size',     label: 'Eyebrow — size (px)',          type: 'number', min: 9,  max: 16,  hint: 'Small uppercase text above headlines.' },
      { key: 'eyebrow_tracking', label: 'Eyebrow — letter spacing',     type: 'text', hint: 'e.g. "2.5px", "0.2em".' },
    ],
  },
  {
    key: 'buttons',
    title: 'Buttons',
    subtitle: 'Shape and size of the primary call-to-action buttons site-wide.',
    icon: '🔘',
    fields: [
      { key: 'radius',         label: 'Corner radius (px)',  type: 'number', min: 0, max: 50, hint: '0 = square, 50 = fully rounded pill.' },
      { key: 'padding_x',      label: 'Horizontal padding (px)', type: 'number', min: 12, max: 60 },
      { key: 'padding_y',      label: 'Vertical padding (px)',   type: 'number', min: 8,  max: 32 },
      { key: 'font_size',      label: 'Font size (px)',       type: 'number', min: 11, max: 24 },
      { key: 'font_weight',    label: 'Font weight',          type: 'select', options: [
        { value:'500', label:'Medium' }, { value:'600', label:'Semibold' }, { value:'700', label:'Bold' }, { value:'800', label:'Extra bold' },
      ]},
      { key: 'text_transform', label: 'Text case',            type: 'select', options: [
        { value:'none', label:'Normal' }, { value:'uppercase', label:'UPPERCASE' }, { value:'capitalize', label:'Capitalize' },
      ]},
      { key: 'letter_spacing', label: 'Letter spacing',       type: 'text', hint: 'e.g. "0.5px", "1px", "0.05em".' },
    ],
  },
  {
    key: 'section_style_home_hero',
    parent: 'section_styles',
    title: 'Home hero — spacing & background',
    subtitle: 'Padding and background for the Home page hero section.',
    icon: '📐',
    fields: [
      { key: 'home_hero_padding_top',    label: 'Padding top (px)',    type: 'number', min: 0, max: 300 },
      { key: 'home_hero_padding_bottom', label: 'Padding bottom (px)', type: 'number', min: 0, max: 300 },
      { key: 'home_hero_bg_color',       label: 'Background color override', type: 'color', hint: 'Leave blank to use the default gradient.' },
      { key: 'home_hero_bg_image',       label: 'Background image',          type: 'image', hint: 'Uploads to the same site-content bucket.' },
    ],
  },
  {
    key: 'section_style_home_staff_picks',
    parent: 'section_styles',
    title: 'Home staff picks — spacing & background',
    subtitle: 'Padding and background for the "Handpicked by our librarians" section.',
    icon: '📐',
    fields: [
      { key: 'home_staff_picks_padding_top',    label: 'Padding top (px)',    type: 'number', min: 0, max: 300 },
      { key: 'home_staff_picks_padding_bottom', label: 'Padding bottom (px)', type: 'number', min: 0, max: 300 },
      { key: 'home_staff_picks_bg_color',       label: 'Background color',    type: 'color' },
      { key: 'home_staff_picks_bg_image',       label: 'Background image',    type: 'image' },
    ],
  },
  {
    key: 'section_style_home_cafe_story',
    parent: 'section_styles',
    title: 'Home cafe story — spacing & background',
    subtitle: 'Padding and background for the "More than a bookstore" section.',
    icon: '📐',
    fields: [
      { key: 'home_cafe_story_padding_top',    label: 'Padding top (px)',    type: 'number', min: 0, max: 300 },
      { key: 'home_cafe_story_padding_bottom', label: 'Padding bottom (px)', type: 'number', min: 0, max: 300 },
      { key: 'home_cafe_story_bg_color',       label: 'Background color',    type: 'color' },
      { key: 'home_cafe_story_bg_image',       label: 'Background image',    type: 'image' },
    ],
  },
  {
    key: 'section_style_about_hero',
    parent: 'section_styles',
    title: 'About hero — spacing & background',
    subtitle: 'Padding and background for the About page hero.',
    icon: '📐',
    fields: [
      { key: 'about_hero_padding_top',    label: 'Padding top (px)',    type: 'number', min: 0, max: 300 },
      { key: 'about_hero_padding_bottom', label: 'Padding bottom (px)', type: 'number', min: 0, max: 300 },
      { key: 'about_hero_bg_color',       label: 'Background color',    type: 'color' },
      { key: 'about_hero_bg_image',       label: 'Background image',    type: 'image' },
    ],
  },
  {
    key: 'section_style_offers_hero',
    parent: 'section_styles',
    title: 'Offers hero — spacing & background',
    subtitle: 'Padding and background for the Offers page hero.',
    icon: '📐',
    fields: [
      { key: 'offers_hero_padding_top',    label: 'Padding top (px)',    type: 'number', min: 0, max: 300 },
      { key: 'offers_hero_padding_bottom', label: 'Padding bottom (px)', type: 'number', min: 0, max: 300 },
      { key: 'offers_hero_bg_color',       label: 'Background color',    type: 'color' },
      { key: 'offers_hero_bg_image',       label: 'Background image',    type: 'image' },
    ],
  },
  {
    key: 'section_style_header',
    parent: 'section_styles',
    title: 'Header — colors',
    subtitle: 'Per-section color overrides for the navbar. Empty = use brand defaults.',
    icon: '🎨',
    fields: [
      { key: 'header_bg_color',          label: 'Background color',   type: 'color', hint: 'Navbar background. Leave blank for the default gradient.' },
      { key: 'header_text_color',        label: 'Text color',         type: 'color', hint: 'Brand name / small tagline.' },
      { key: 'header_link_color',        label: 'Nav link color',     type: 'color' },
      { key: 'header_link_active_color', label: 'Active link color',  type: 'color', hint: 'Current page link.' },
    ],
  },
  {
    key: 'section_style_footer',
    parent: 'section_styles',
    title: 'Footer — colors & alignment',
    subtitle: 'Per-section color and alignment overrides for the footer.',
    icon: '🎨',
    fields: [
      { key: 'footer_bg_color',      label: 'Background color', type: 'color' },
      { key: 'footer_text_color',    label: 'Body text color',  type: 'color' },
      { key: 'footer_heading_color', label: 'Heading color',    type: 'color', hint: 'Quick Links / Hours / Contact headings.' },
      { key: 'footer_link_color',    label: 'Link color',       type: 'color' },
      { key: 'footer_text_align',    label: 'Text alignment',   type: 'select', options: [
        { value: 'left',   label: 'Left' },
        { value: 'center', label: 'Center' },
        { value: 'right',  label: 'Right' },
      ] },
    ],
  },
  {
    key: 'section_style_home_genres',
    parent: 'section_styles',
    title: 'Home genres — colors & alignment',
    subtitle: '"Browse by genre" section colors.',
    icon: '🎨',
    fields: [
      { key: 'home_genres_bg_color',    label: 'Background color', type: 'color' },
      { key: 'home_genres_text_align',  label: 'Text alignment',   type: 'select', options: [
        { value: 'left',   label: 'Left' },
        { value: 'center', label: 'Center' },
        { value: 'right',  label: 'Right' },
      ] },
    ],
  },
  {
    key: 'section_style_home_new_arrivals',
    parent: 'section_styles',
    title: 'Home new arrivals — colors & alignment',
    subtitle: '"New & noteworthy" section colors.',
    icon: '🎨',
    fields: [
      { key: 'home_new_arrivals_bg_color',   label: 'Background color', type: 'color' },
      { key: 'home_new_arrivals_text_align', label: 'Text alignment',   type: 'select', options: [
        { value: 'left',   label: 'Left' },
        { value: 'center', label: 'Center' },
        { value: 'right',  label: 'Right' },
      ] },
    ],
  },
  {
    key: 'section_style_home_newsletter',
    parent: 'section_styles',
    title: 'Home newsletter — colors & alignment',
    subtitle: 'Newsletter subscribe section.',
    icon: '🎨',
    fields: [
      { key: 'home_newsletter_bg_color',   label: 'Background color', type: 'color' },
      { key: 'home_newsletter_text_align', label: 'Text alignment',   type: 'select', options: [
        { value: 'left',   label: 'Left' },
        { value: 'center', label: 'Center' },
        { value: 'right',  label: 'Right' },
      ] },
    ],
  },
];

// Map a "dotted field path" (e.g. "about.values_1_title") to the schema
// section key that contains it. Sections with `parent` are grouped under
// the parent's real storage key in DEFAULT_CONTENT. Used by click-to-edit.
export function sectionForFieldPath(fieldPath) {
  const [section, field] = fieldPath.split('.');
  for (const s of CONTENT_SCHEMA) {
    const storageKey = s.parent || s.key;
    if (storageKey === section && s.fields.some(f => f.key === field)) {
      return s.key;
    }
  }
  return null;
}
